### ISSUE TITLE
没有记错的话这里应该是 “施肥” ？

### ISSUE THREAD

**Issue by xzthemeofsss** [junbaor/jike-cli#1]
https://github.com/junbaor/jike-cli/blob/b32b554caf50ca772b55db978636be3febdc6da2/src/main/java/com/github/junbaor/jike/cmd/Nbdz2021Cmd.java#L35

**Comment by junbaor** [comment]
对对对，按照字面翻译了, 已修改 https://github.com/junbaor/jike-cli/commit/0d3b710e72f3df118dfef2baa1d7c8ad8e831979
