### ISSUE TITLE
homebrew 查不到了

### ISSUE THREAD

**Issue by bazinga-7** [junbaor/jike-cli#2]
homebrew 找不到了，但是java项目还能用。怎么不更homebrew啦？

**Comment by junbaor** [comment]
@bazinga-7 

homebrew 应该没问题, 你使用的安装命令是下面这个吗？
```
brew install junbaor/brew/jike-cli
```

最新的一个版本是有关南北大战的`外挂`, 不太想让太多人可以轻松使用。
